---
title: 'usheR'
date: '2024-10-12'
format: gfm
---

<!-- Do not manually edit `README.md` -->
<!-- Edit the `README.qmd`, then render. -->
<!-- Also commit and push changes to this and the resulting README.md file. -->
<!-- This makes is easy to incorporate code examples later if we choose. -->

Some helper functions for teaching.

When you add any functions to the package, make your changes in a separate Git branch, and submit a pull request (PR).
As part of your changes, you should also add your name to the `DESCRIPTION` file (see below).
You can also include a comment with your ORCID number if you like, in the `comment` field.
To add your name use the following template and paste it into the `Authors@R:` field.

```
person(
  given   = "Given name",
  family  = "Family name",
  email   = "email@example.com",
  role = "aut",
  comment = c(ORCID = "Optional - YOUR-ORCID-ID")
)

```
For example, inside the `c()` following `Authors@R:`

```
Authors@R: c(
    person("John", "Wilson",
    email = "43386915+jmcvw@users.noreply.github.com", role = c("aut", "cre"))
    )
```


Then, commit and push, and submit your PR.
If PRs are new to you, maybe we can cover this in a future week?


__Extra notes:__

- Please do not use `library()` __ANYWHERE__ in the package.
    - in particular don't do `library(tidyverse)`
    - (For good reasons, not any kind of anti-tidyverse sentiment)
    
    
## Instructions for end-users of this package:

### Pair Maker:

TODO

### Simplified Classnotes Updater (no-drama github pull-and-merge):

This part of the package allows students to 'update/pull' most recent notes from teacher's public course git repository without using git commands in terminal or RStudio. This is especially useful on the beginner courses, and in the first weeks where you want to start using R code quickly, prior to teaching students abotu git.

**How To use it:**

**As a Teacher:**

- This assumes you have all your class notes for students in a github repo, which includes the RStudio project
- Include the [student-facing file](/resources/RUN_TO_GET_RECENT_NOTES.Rmd) from this package in the top folder of your teaching-notes repo.
- This file installs UsheR package and runs a function from it. That function runs a git commit-merge-pull flow behind the scenes (so that students does not need to). Any conflicts are dealt with gracefully (by keeping both student and teacher copy, with a timestamp).

**Students:**

- Once, on the beginning of the course, students will need to clone your teaching repo using RStudio menu interface (using `File > New Project > Version Control > Git` and use your Repository Url). 
- Whenever students want to have the most recent version of the class notes (e.g. every week) they need to open RStudio and run the code block in file `RUN_TO_GET_RECENT_NOTES.Rmd`.
- This should work both on local RStudio, PositCloud and Noteable.
